### ISSUE TITLE
Trigger load more never stops

### ISSUE THREAD

**Issue by nazarposhta** [CassetteRocks/react-infinite-scroller#14]
Why the loadMore={loadFunc} works all the time? 
Although the page of items is full ?

**Comment by danbovey** [comment]
I've found that the loadMore function runs infinitely if I load in a page of items but the `loader` isn't styled to `clear: both`, so the InfiniteScroll component doesn't have a proper height. Also it might be worth using underscore or lodash so that you can throttle the requests you make to the server.

```js
constructor(props) {
    ...
    this.loadMore = _.throttle(this.loadMore, 600);
}
```

**Comment by nazarposhta** [comment]
_.throttle - is not very nice solution actually
- class "clearfix" (clear: both;) resolved this problem
thanks

**Comment by acomito** [comment]
@nazarposhta what are you applying clear:both to? infinite scroll?

I'm trying to use the window as the trigger, but as soon as my page loads, it is just firing loadMore function as many times as it can before hasmore goes false

```
return (
			<div>
			<InfiniteScroll
				style={{height: '100vh'}}
			    loadMore={this.onLoadMore}
			    hasMore={data.posts.length < postsCount.postsCount.count}
			    loader={<div>Loading ...</div>}
			>
				{data.posts.map( item => {
					//return <div key={item._id} style={{height: 100}}>{item.title}</div>
					return <PostCard key={item._id} item={item} user={user} />
				})}
			</InfiniteScroll>
			{(data.posts.length < postsCount.postsCount.count) === false && <div>NO MORE POSTS</div>}
			</div>
		);
```

**Comment by danbovey** [comment]
The comment I had above says that the element passed into the `loader` prop wasn't correctly styled with `clear: both`. You are passing in `<div>Loading ...</div>` so that may need to be styled to stop endless firing.

**Comment by nazarposhta** [comment]
@danbovey Exactly

**Comment by acomito** [comment]
@danbovey styled how?

**Comment by gibbitz** [comment]
I'm using flexbox and have no floats in my layout. Are you adding floats to the elements directly or is this not my problem? I can get it to not load all "pages" if I make the page very short, but as soon as I scroll I get all the pages. Looking at similar bugs now, but wanted to rule this one out first.

**Comment by gibbitz** [comment]
Posting back. I can see now that the example file is updating the page number used for determining `hasMore` after the return of the fetched data. Due to my architecture, I don't have direct access to the promise chain (using non-thunk redux action creators), so I was using the returned pageLoaded + 1 from the `loadMore` parameters. Seems like I need to be more restrictive since the DOM is empty while waiting for the first results I end up making all my calls before the container fills up enough for the offset condition in `scrollListener` to catch. Basically I'm sharing my stupidity here to hopefully help someone in posterity similarly challenged as myself.
