### ISSUE TITLE
🤔 Container scrolls back to top when new data is loaded

### ISSUE THREAD

**Issue by shivekkhurana** [CassetteRocks/react-infinite-scroller#156]
I'm using this Component with `useWindow` set to false and the height of the parent set to `64vh`.

The loader works just fine, calls the api at the end of the list, but when new data is loaded, it scrolls to the top of the list. 

I'm using redux here. My code looks like this : 
```jsx
<div style={{height}} className={`overflow-y-scroll ${className}`}>
    <ReactInfiniteScroll
      loadMore={onEndReached}
      hasMore={hasMore}
      loader={loader}
      useWindow={useWindow}
      threshold={8}
      // initialLoad={false}
    >
      {children}
    </ReactInfiniteScroll>
  </div>
```
and the children here are : 
```jsx
{conversations.map(c => <Row key={c.id} conversation={c}/>)}
```

Thanks.

**Comment by shivekkhurana** [comment]
Seems related to #124

**Comment by danbovey** [comment]
If you think it's related to 124, the fix is to add a unique key prop to your `loader` component.

**Comment by shivekkhurana** [comment]
I have added a unique key prop to loader. But the problem still persists.

**Comment by danbovey** [comment]
I recently updated the issue templates on this repo so that I can identify the bugs with this repo.

Please clone your layout and use of react-infinite-scroller by forking [this Code Sandbox](https://codesandbox.io/s/my6vo3yo78) and linking it here. Doing so will massively expedite getting the bug fixed! 👊

**Comment by dlbnco** [comment]
I think this is not a bug, but rather the way you update the data in your store. I was facing the same problem and realized that the way I was updating the list of items on `loadMore` was having an impact on how the scroll state reacted to those changes.

In my case, I was using `Array.proptotype.reverse()` at the component level to render my list in a descending order, and that was the cause of the problem. I moved the `reverse()` function to the action instead, and the problem was gone.

**Comment by shivekkhurana** [comment]
I figured that it was a bug in my rendering logic that removed and added the listview back each time.

This gave me the impression that the list view scrolled back to the top, but in reality, it was being re-rendered. Closing the issue as there is nothing wrong with this library. 

Thanks

**Comment by baguskah** [comment]
just happened to me. Try refresh the browser with the current react-infinite-scroller page the problem is hiding. How to solve this ?

**Comment by ilkermutlu** [comment]
@dlbnco I know it has been some time since this, but any change you can share what your reducer looks like?

I've tried 
```
items: state.items.concat(action.payload.data)
```
and
```
items: [...state.items, ...action.payload.data]
```
no luck. the component still scrolls to top when new items are appended.

**Comment by shivekkhurana** [comment]
@ilkermutlu The reducer that worked for me looked like:
```js
 return {...state, commentCreateErrors: [], comments: [action.payload.comment].concat(existingComments)};
```

My usecase was to add a message on top. However this code is multiple years old.

**Comment by ilkermutlu** [comment]
@shivekkhurana thanks.

Turns out mine doesn't have to do anything with the reducer as well. I think I solved it by updating my render logic. Just the same as you guys.
