### ISSUE TITLE
Will you help with this?

### ISSUE THREAD

**Issue by akhilpab** [CassetteRocks/react-infinite-scroller#18]
I'm using this with backbone. But I'm not getting expected result. the browser is keep on hitting the server and getting the data. I didn't even started scrolling. It's not getting stopped.

**Comment by danbovey** [comment]
Check out my answer to #14, as it may be similar.

Because this component is very simple it doesn't control how you make requests and when and when not to trigger. Therefore, you have to make sure that the items are loaded in and the container has a computed height (if you're floating elements, use `clear: both`).
