### ISSUE TITLE
Loader component not shown

### ISSUE THREAD

**Issue by loripino21** [CassetteRocks/react-infinite-scroller#207]
**Describe the bug**
The Loader progress component is not shown, even if specified in loader attribute.

**To Reproduce**
Just look at your demo page https://cassetterocks.github.io/react-infinite-scroller/demo/
No loading animation is shown at all.

**Expected behavior**
At the end of the list, a loader indicator appears.

**Device (please complete the following information):**
 - OS:  Win
 - Browser Chrome
 - Version npm 1.2.4

**Comment by ryk0v** [comment]
Actually it's showing the "loading..." message at the bottom of the list in the demo.  
It seems that loader is visible all the time, until InfinityScroll component receives hasMore prop equal to false. 
It might be that you are setting hasMore flag to false, while fetching additional items from the server in order to prevent loadMore function from triggering again.

**Comment by loripino21** [comment]
Sorry i later discovered that was a problem of mine.
