### ISSUE TITLE
Throttle scrollListener

### ISSUE THREAD

**Issue by jabacchetta** [CassetteRocks/react-infinite-scroller#22]
Would be nice to have a throttle option for the scrollListener function (limit firing of the event). Could probably pull most of the code from [underscore](http://underscorejs.org/#throttle).

**Comment by danbovey** [comment]
It would be nice but I'm gonna say it's out of scope of this simple infinite scroll package because I like the fact it doesn't dictate how you have to loads items. It doesn't depend on it's own XHR library, so it shouldn't throttle the function that you're meant to write to load your items using your app's existing way of loading things.

**Comment by duhaime** [comment]
Can this thread be reopened? It's come up several times and would be great to save the JS cycles that trigger on scroll...
