### ISSUE TITLE
Permanent loading of more results in iFrame with dynamic height

### ISSUE THREAD

**Issue by Regaddi** [CassetteRocks/react-infinite-scroller#46]
Hi,

I encountered a sweet little problem when using the InfiniteScroller inside of an iFrame.
The iFrame is called a ContentFrame in the Content Management System.
The CMS Editor UI automatically updates the iFrames height to the documents height to prevent the iFrame from having scrollbars.

This triggers a permanent loadMore in the InfiniteScroller.
I think the calculation for the threshold value is currently not flexible enough to cover this case.

**Comment by danbovey** [comment]
Hi

I don't think that's an issue that can be fixed by the component. The logic for scrolling and meeting the threshold is perfectly fine. If your iframe height becomes equal to the component height, that means the bottom of the scroll area has been "reached" and it will trigger a load, there's no way around that.

I think the solution here is to use the `useWindow={false}` prop so that the height of the component is linked to the height of the parent element of the component, instead of the iframe.

```js
<div style={{overflowY:'auto',height:'600px'}}> // Could set this dynamically with JS so it's the height of the window or container (maybe look into react-dimensions)
    <InfiniteScroll
        useWindow={false}
    >
        {items}
    </InfiniteScroll>
</div>
```

**Comment by danbovey** [comment]
If you've found a workaround or solution, or can provide more info please let me know, else I'll be closing this issue soonish.

**Comment by Regaddi** [comment]
Well, the workaround is to disable the rendering of the application inside the authors UI.
I could try to check for a window.top element, but I'm not sure if this will work out.
