### ISSUE TITLE
Dom scroll parent with unfixed height

### ISSUE THREAD

**Issue by DenizTemizer** [CassetteRocks/react-infinite-scroller#51]
Currently working on a project where the wrapper, which can be scrolled, has following styling:

```CSS
.style {
    height: 100%;
    overflow-y: auto;
}
```

In this case offset needs to be calculated like this:
```javascript
offset = el.parentNode.scrollHeight - el.parentNode.scrollTop - el.parentNode.clientHeight;
```

instead of this:
```javascript
offset = el.scrollHeight - el.parentNode.scrollTop - el.parentNode.clientHeight;
```

How about a prop (boolean) relativeParentHeight?

**Comment by danbovey** [comment]
I'll test this out as soon as I can.

Something I've recommended to a lot of people who don't have flexibility with the `parentNode` of the component is to use [react-dimensions](https://github.com/digidem/react-dimensions). So you could use that on the wrapper to take up the height of the parent container instead of styling it `height: 100%`.
