### ISSUE TITLE
loadMore not called

### ISSUE THREAD

**Issue by alexandru-tomescu** [CassetteRocks/react-infinite-scroller#68]
`loadMore() {
	console.log('------> LOAD MORE')
	this.setState({
		...this.state,
		pageStart: this.state.pageStart++
	})
}`

`<InfiniteScroll
	initialLoad={ false }
		pageStart={ this.state.pageStart }
		loadMore={ this.loadMore }
		hasMore={ this.state.hasMore } /* always true */
		threshold={ 50 }
		useWindow={ false }
		loader={ loader }>
        ...content
</InfiniteScroll>`

loadMore function is not called. Can you tell me please why i'm encountering this problem ?

thank you !

**Comment by danbovey** [comment]
First off, when you call `setState` you don't need to pass in the whole state with `...this.state`. On your behalf, React uses something like `Object.assign` to merge the new state you set with the current state - However, it doesn't clone deeply so if you're adding to an object, it's fine at that point to use the spread operator: `setState({ obj: { ...this.state.obj, newItem } })`.

Also, don't use the `++` incrementer with `setState`, because, again, you're mutating `pageStart` instead of setting, if you need lines like that make sure to use `{ pageStart: this.state.pageStart + 1 }`.

I think the actual problem with why it's not updating is because you're not meant to update the `pageStart` prop. If you want to keep a record of which page your on yourself, keep `page` in your state and update it in your `loadMore`. If you want InfiniteScroller to manage your pagination, use the `page` parameter that is given to `loadMore`

```js
// this.state.page = 0
loadMore() {
    const nextPage = this.state.page + 1;
    this.setState({ page: nextPage });
    request.get(`/search?page=${nextPage}`)
}
```

-- or --

```js
loadMore(page) {
    request.get(`/search?page=${page}`)
}
```

**Comment by alexandru-tomescu** [comment]
I tried like you said to me. No luck. loadMore is not called at all. Weird...

This is my code:
<pre><code>
import React, { PropTypes, Component } from 'react'
import { injectIntl, intlShape } from 'react-intl'
import { Card, CardText, List, ListItem } from 'react-toolbox'
import { Loader } from '../../../commons'
import InfiniteScroll from 'react-infinite-scroller'
import moment from 'moment'

class UserActivityItemsList extends Component {
	constructor(props) {
		super(props)
		this.state = {
			hasMore: true,
			pageStart: 0
		}
	}

	loadMore() {
		console.log('------> LOAD MORE')
		const nextPage = this.state.pageStart + 1
		this.setState({
			pageStart: nextPage
		})
	}

	render() {
		return (
			<InfiniteScroll
				initialLoad={ false }
				pageStart={ this.state.pageStart }
				loadMore={ this.loadMore }
				hasMore={ this.state.hasMore }
				threshold={ 50 }
				useWindow={ false }
				loader={ <div>Loading ...</div> }>
				<Card>
					<List>
						{ items... }
					</List>
					<Loader
						displayIf={ this.props.isFetching }
						type='circular'
						primaryMessage={ this.props.intl.formatMessage({ id: 'generalFetchingDataDots' }) } />
				</Card>
			</InfiniteScroll>
		)
	}
}

UserActivityItemsList.propTypes = {
	intl: intlShape
}

export default injectIntl(UserActivityItemsList)
</code></pre>

**Comment by alexandru-tomescu** [comment]
Working now man

<code>
style={{overflowY: 'auto', height: '100vh'}}
</code>

Thank you ! :)

**Comment by danbovey** [comment]
Should get around to making an FAQ on the README because every other issue I get for this package is about `overflow-y` or `clear`

**Comment by JoaoCnh** [comment]
I have a container with 500px height and overflow-y: auto;

In the config I'm not using the Window. ( e.g: useWindow={false} )

And loadMore never gets called.

I already tried messing around with various values from threshold but still no call.

Can anyone help?

**Comment by JoaoCnh** [comment]
It's because of my animation TransitionGroup. Any tips for scrolling with Animation?
